### ISSUE TITLE
Qt5.9编译函数调用错误是什么原因

### ISSUE THREAD

**Issue by Yuxiangfei** [Skiars/SerialTool#15]
SendScintilla(SCI_SETKEYWORDS, (unsigned long)0, g_szKeywords);// 设置关键字

219: error: call of overloaded 'SendScintilla(QsciScintillaBase::<anonymous enum>, long unsigned int, const char*&)' is ambiguous
     SendScintilla(SCI_SETKEYWORDS, (unsigned long)0, g_szKeywords);// 璁剧疆鍏抽敭瀛

**Comment by infraredZ** [comment]
我也是这里的问题，那个SCI_SETKEYWORDS 宏没有高亮。

**Comment by Skiars** [comment]
这应该是新版的 QScintilla 有问题

**Comment by pokebox** [comment]
Qt 5.10.1编译时也是这里出了问题。QScintilla应该使用什么版本的？ @Skiars

**Comment by Skiars** [comment]
用 2.10.3 的QScintilla不会有问题，太老的版本我也没有测试
