### ISSUE TITLE
有个不明白的地方，希望指点

### ISSUE THREAD

**Issue by crsc-hrh** [Skiars/SerialTool#17]
portmanager.cpp中，line61，delete m_currentPort;被执行后，怎么还调用
m_currentPort->loadConfig(config);这行代码

**Comment by Skiars** [comment]
[`setupPort`](https://github.com/Skiars/SerialTool/blob/3bdef50da27232cc73bde4cfcadd619480815300/SerialTool/src/port/portmanager.cpp#L105) 函数重新设置了 `m_currentPort`

**Comment by crsc-hrh** [comment]
明白了！谢谢。
