### ISSUE TITLE
Qt5.10.1 使用QScintilla2.10.8/2.11.1编译报错

### ISSUE THREAD

**Issue by pokebox** [Skiars/SerialTool#19]
textedit.o: In function `TextEdit::onTextChanged()':
textedit.cpp:(.text+0xac): undefined reference to `QsciScintilla::text() const'
textedit.cpp:(.text+0x134): undefined reference to `QsciScintillaBase::SendScintilla(unsigned int, int) const'
textedit.cpp:(.text+0x150): undefined reference to `QsciScintillaBase::SendScintilla(unsigned int, int) const'
textedit.cpp:(.text+0x164): undefined reference to `QsciScintillaBase::SendScintilla(unsigned int, unsigned long, long) const'
textedit.o: In function `TextEdit::setMarginsWidth()':
textedit.cpp:(.text+0x27c): undefined reference to `QsciScintillaBase::SendScintilla(unsigned int, unsigned long, long) const'
textedit.o: In function `TextEdit::onLinesChanged()':
textedit.cpp:(.text+0x3bc): undefined reference to `QsciScintillaBase::SendScintilla(unsigned int, unsigned long, long) const'
textedit.o: In function `TextEdit::highlightNone()':
textedit.cpp:(.text+0x480): undefined reference to `QsciScintillaBase::SendScintilla(unsigned int, int) const'
textedit.o: In function `TextEdit::highlightCpp()':
textedit.cpp:(.text+0x4a0): undefined reference to `QsciScintillaBase::SendScintilla(unsigned int, int) const'
textedit.cpp:(.text+0x4bc): undefined reference to `QsciScintillaBase::SendScintilla(unsigned int, unsigned long, char const*) const'
……省略中间部分……
moc_textedit.o:(.data.rel.ro._ZTV8TextEdit[_ZTV8TextEdit]+0x448): undefined reference to `QsciScintilla::undo()'
moc_textedit.o:(.data.rel.ro._ZTV8TextEdit[_ZTV8TextEdit]+0x450): undefined reference to `QsciScintilla::unindent(int)'
moc_textedit.o:(.data.rel.ro._ZTV8TextEdit[_ZTV8TextEdit]+0x458): undefined reference to `QsciScintilla::zoomIn(int)'
moc_textedit.o:(.data.rel.ro._ZTV8TextEdit[_ZTV8TextEdit]+0x460): undefined reference to `QsciScintilla::zoomIn()'
moc_textedit.o:(.data.rel.ro._ZTV8TextEdit[_ZTV8TextEdit]+0x468): undefined reference to `QsciScintilla::zoomOut(int)'
moc_textedit.o:(.data.rel.ro._ZTV8TextEdit[_ZTV8TextEdit]+0x470): undefined reference to `QsciScintilla::zoomOut()'
moc_textedit.o:(.data.rel.ro._ZTV8TextEdit[_ZTV8TextEdit]+0x478): undefined reference to `QsciScintilla::zoomTo(int)'
moc_textedit.o:(.data.rel.ro+0x0): undefined reference to `QsciScintilla::staticMetaObject'
collect2: error: ld returned 1 exit status
Makefile:429: recipe for target 'SerialTool_pre' failed
make: *** [SerialTool_pre] Error 1

**Comment by Skiars** [comment]
请看这个issue https://github.com/Skiars/SerialTool/issues/15

**Comment by Skiars** [comment]
这个问题已经被修复了
