### ISSUE TITLE
自己编译的程序比原作者发布的程序少了设置选项的界面，这是怎么回事？

### ISSUE THREAD

**Issue by tumuyan** [Skiars/SerialTool#26]
原作者发布的界面，点击选项是有内容的
![image](https://user-images.githubusercontent.com/3126801/87881588-de968680-ca2c-11ea-9b82-d55f26c45ed6.png)

我使用最新代码直接编译，点击选项是空的
![image](https://user-images.githubusercontent.com/3126801/87881603-fa019180-ca2c-11ea-90cb-cccc867d6ddc.png)

使用选项中的文本"Opacity"匹配大小写进行搜索整个项目，没有这个字符串
![image](https://user-images.githubusercontent.com/3126801/87881713-a80d3b80-ca2d-11ea-8751-1ba694c55ae0.png)

因此我认为代码缺失了一部分，作者可以补完嘛？或者有好心人补一下嘛？或者我编译的有问题，指教下哪里出错了？

**Comment by Skiars** [comment]
把源码的 SerialTool/config 文件夹拷到 SerialTool.exe 同目录下:

![image](https://user-images.githubusercontent.com/16442186/87894410-4375cf00-ca75-11ea-9f11-e9ff8d190103.png)

**Comment by tumuyan** [comment]
谢谢 现在已经好了

**Comment by taotieren** [comment]
Linux 下这个 config 目录放在什么地方呢？

**Comment by Skiars** [comment]
放到可执行文件的目录下试试看

**Comment by taotieren** [comment]
> 放到可执行文件的目录下试试看

编译的时候遇到一些新的问题在这里回复了
https://github.com/Skiars/SerialTool/pull/32

**Comment by Skiars** [comment]
> > 放到可执行文件的目录下试试看
> 
> 编译的时候遇到一些新的问题在这里回复了
> #32 

好的
